on:
  push:
    branches:
      - master

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: ${{ vars.GIT_SYNC_SOURCE_REPO }}
          source_branch: ${{ vars.GIT_SYNC_SOURCE_BRANCH }}
          destination_repo: ${{ vars.GIT_SYNC_DESTINATION_REPO }}
          destination_branch: ${{ vars.GIT_SYNC_DESTINATION_BRANCH }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
